package com.mintmedical.ycwebsite.dao;

import com.mintmedical.ycwebsite.entity.Contactus;
import java.util.List;

public interface ContactusMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contactus
     *
     * @mbggenerated
     */
    int insert(Contactus record);
}